### ISSUE TITLE
What do we need external API KEY ?

### ISSUE THREAD

**Issue by guillaume-xrpl** [Aaditya-T/xrpl-wallet-connect#1]
Hello, 

Thanks for the work you have done with this wallet connector. 

But I don't understand why do you need an API KEY from a specific wallet if you're supposed to be able to connect from any wallet ?

Best regards.

**Comment by Aaditya-T** [comment]
Hey @guillaume-xrpl,

The answer to your question is: XAMAN (Formerly xumm) has an api with which you have to connect to perform actions like create a qr code for signing in, checkl if the user has signed in, and xumm also offers a developer console which shows you your past api requests, xapp configurations, etc! 

Basically, xaman offers a lot of stats, logs, configs - and with api keys the platform tracks your usage, rate limits, logs, etc! Thats why xaman requires an api key as it has to track the requests made by each developer - this also ensures that not just anyone can spam request to the xaman api without authorized access.

Though - the api key only needs to be implemented by the developer of course, once you have the api key integrated, then anyone can sign in into your application! 
> **NOT EVERY USER WHO IS SIGNING NEEDS AN API KEY, ONLY THE DEVELOPER NEEDS TO IMPLEMENT IT ONCE.**

### XAMAN Docs
Here are the xaman docs for your reference: 
[Xaman Docs](https://docs.xumm.dev/)
[API Reference](https://xumm.readme.io/reference/about)
[Developer Console](https://apps.xumm.dev/)

**Comment by guillaume-xrpl** [comment]
Hey @Aaditya-T, 

Thanks for your answer. Ok I wasn't aware of that, this is the first time I see API keys to connect to a wallet. I'll have a look at the documentation. 

Best.
